apiVersion: apps/v1
kind: Deployment
metadata:
  name: idm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idm
  template:
    metadata:
      labels:
        app: idm
    spec:
      containers:
        - name: idm
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080