apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: {{ .Values.eurekaserver.image.repository }}:{{ .Values.eurekaserver.image.tag }}
          ports:
            - containerPort: 8080